### ISSUE TITLE
pyagsapi dev planning

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/pyagsapi#30]
## Tasks

+ [x] Refactor backend to use [`AGS4.check_file()`](https://gitlab.com/ags-data-format-wg/ags-python-library/-/blob/main/python_ags4/AGS4.py#L602) rather than the CLI (JSON response)
+ [x] Refactor backend to use [`AGS4.check_file()`](https://gitlab.com/ags-data-format-wg/ags-python-library/-/blob/main/python_ags4/AGS4.py#L602) rather than the CLI (text response)
+ [x] Add dictionary selection as query parameter to API
+ [x] Refactor backend to handle dictionary selection
+ [x] Refactor backend `convert` function to use library instead of CLI
+ [x] Refactor API to handle updated `convert`
+ [x] Add integration tests to other routes and formats
+ [x] Add endpoint to do BGS data validation steps
+ [x] BGS rule for coordinates in LOCA
+ [x] BGS rule for SAMP integrity
+ [x] BGS rule for groups and headings
+ [x] Flag and reject AGS3 (test/files/real/19684.ags)
+ [x] Catch mismatched columns (test/files/real/JohnStPrimarySchool.ags)
+ [x] In LOCA - TYPE for LOCA_NATE/NATN/LOCX/LOCY should be 2DP 
+ [x] Add file summary below metadata: 
- 1 data rows in PROJ group.
- 2 data rows in LOCA group.
- 24 groups identified in file
- DICT is present for user defined groups / DICT is not present - there are no user defined groups
  - Check covered by AGS check rule 9   
-  FILE group is not present but is only required if submission includes non-AGS file 

![image](https://user-images.githubusercontent.com/33657876/134477250-299ed7dc-4098-417c-b700-052085d8b3b2.png)

Bonus - 

+ [x] Make root URL user configurable (via environment variable)
+ [ ] Fix UnboundLocalError bug in upstream repo
+ [ ] Make logging messages from `bgs.py` and `ags.py` print to console
+ [ ] Add endpoint to automatically clean files - `dataclean`
+ [x] Report / fix "convert asks for user input" bug in upstream repo - https://gitlab.com/ags-data-format-wg/ags-python-library/-/issues/22 ADD COMMENTS
+ [x] Report/fix `sys.exit()` calls in upstream library
+ [x] Submit MR to fix the above
+ [x] Add 50 Mb file size limit- Done via k8s NGINX config
+ [ ] Add `to_html` function to backend
+ [ ] Add `to_html` parameter to API

## Questions

+ Do we just remove `v1` code, given than there are no real users yet?

#### `/api/v1/?validatedata?`

POST: Binary upload of file
Response: `{"result": "true"}` ?
Errors: 400 - some problem with uploaded file

#### `/api/v1/?clean?`

POST: Binary upload of file
Response: `{"result": "true"}` ?
Errors: 400 - some problem with uploaded file

### Backend function specification

```python
def validatedata(filename: Path) -> Dict:
    # return Dictionary / JSON with data errors
    pass
```
#### Schema

```
class Validation(BaseModel):
    filename: str = Field(..., example="example.ags")
    filesize: str = Field(None, example="1 kB")
    checker: str = Field(None, example="python_ags4 v0.3.6")
    dictionary: str = Field(None, example="Standard_dictionary_v4_1.ags")
    time: str = Field(None, example="2021-08-18 09:23:29")
    message: str = Field(None, example="7 error(s) found in file!")
    results: Dict = Field(None, example="")
```
from:

```
{'Rule 2a': [{'line': 1,
   'group': '',
   'desc': 'Is not terminated by <CR> and <LF> characters.'}],
 'Rule 3': [{'line': 1,
   'group': '',
   'desc': 'Does not start with a valid data descriptor.'}],
 'Rule 5': [{'line': 1,
   'group': '',
   'desc': 'Contains fields that are not enclosed in double quotes.'}],
 'Rule 13': [{'line': '-', 'group': 'PROJ', 'desc': 'PROJ table not found.'}],
 'Rule 14': [{'line': '-', 'group': 'TRAN', 'desc': 'TRAN table not found.'}],
 'Rule 15': [{'line': '-', 'group': 'UNIT', 'desc': 'UNIT table not found.'}],
 'Rule 17': [{'line': '-', 'group': 'TYPE', 'desc': 'TYPE table not found.'}],
 'Metadata': [{'line': 'File Name', 'group': '', 'desc': 'nonsense.ags'},
  {'line': 'File Size', 'group': '', 'desc': '0 kB'},
  {'line': 'Checker', 'group': '', 'desc': 'python_ags4 v0.3.6'},
  {'line': 'Dictionary', 'group': '', 'desc': 'Standard_dictionary_v4_1.ags'},
  {'line': 'Time (UTC)', 'group': '', 'desc': '2021-08-23 13:19:46'}]}
```

### Discussion

+ Default to creating JSON response.  For text response, use Jinja2 to render a text version.

**Comment by KoalaGeo** [comment]
Closing as ongoing tasks moved to https://github.com/BritishGeologicalSurvey/pyagsapi/issues/59
